[package]
name = "hkx_serde"
version.workspace = true
description = ""
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
rust-version = "1.69"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4"
byteorder = "1.5"
derive-new = "0.6"
indexmap = "2.2"
num-derive = "0.4"
num-traits = "0.2"
ordered-float = { version = "4.2.0", features = ["serde"] }
parse_int = { version = "0.6" }
quick-xml = { version = "0.31", features = ["serialize", "serde-types"] }
# rust-ini = { version = "0.21" }
serde = { version = "1.0", features = ["derive"] } # Implement (De)Serializer
thiserror = "1.0"                                  # define errors type
# tokio = { version = "1.36.0", features = [
#   "fs",
#   "io-util",
#   "macros",
#   "rt",
#   "rt-multi-thread",
# ] } # Async Executor
tracing = "0.1" # Logger
# xml-doc = { version = "0.2" }
zerocopy = { version = "0.7", features = ["derive", "simd"] }
zerovec = { version = "0.10", features = ["derive"] }
static_assertions = "1.1"

[dev-dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
pretty_assertions = "1.4"
quick_tracing = { version = "0.1.5", features = ["derive"] }
