name: Cargo Lint & Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          prefix-key: cargo-${{ matrix.platform }}

      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Lint Check
        run: cargo clippy --workspace -- -D warnings

      # https://nexte.st/docs/installation/pre-built-binaries/#using-nextest-in-github-actions
      - name: Install nextest(Parallel Test Execution CLI)
        uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo nextest run --workspace

      - name: Run build
        run: cargo build

      - name: Generate
        run: cargo xtask generate

      - name: Generate(For Nemesis)
        run: cargo xtask generate --nemesis

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hk_2010.2.0-r1 json(Normal & Nemesis)
          path: |
            ${{ github.workspace }}/crates/hkx_class_generator/assets/classes
            ${{ github.workspace }}/crates/hkx_class_generator/assets/nemesis
